services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports: 
      - "3001:3001"
      - "9229:9229"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      BB2_APP_LAUNCH: ${BB2_APP_LAUNCH:-start}
    ports:
      - "3000:3000"
